

image: 
  - Visual Studio 2017
  - Ubuntu

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true



build: off
    

# to run your custom scripts instead of automatic MSBuild
build_script:
    - sh: |
            cd ./ClientTLS
            sudo cp ca-server.pem /etc/ssl/certs
            sudo cp lets-encrypt-x3-cross-signed.pem.txt /etc/ssl/certs/lets-encrypt-x3-cross-signed.pem
            echo -e "GET / HTTP/1.1\r\nHost: admin.mediagoom.com\r\nConnection: close\r\n\r\n" | openssl s_client -connect admin.mediagoom.com:444 -key ./openid-key.pem -cert ./openid.pem -quiet
            dotnet run
    - ps: |
            cd ./ClientTLS
            Import-Certificate -FilePath ca-server.pem  -CertStoreLocation 'Cert:\LocalMachine\Root' -Verbose
            dotnet run
            
